[Interface]
# Konfiguration für Stern
#
# Remote Server IP-Adresse : 10.3.41.35
#      Verbindung über SSH : ssh ubuntu@10.3.41.35
#             mit Passwort : peFai1ee
#
# Lokale Maschine          : 10.3.41.85

Address = 10.3.41.85/24
PrivateKey = oBMAMv9ib7SrFpDuL4V4GhjtFgUoDotKmE9397ILb0U=

[Peer]
PublicKey = 0eWH4go8yMYwVBGPTtPMusCgT14XSYsbtx6d983Yhm0=
Endpoint = cloud.tbz.ch:51933

AllowedIPs = 10.3.41.0/24
